In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("20230122-062257.csv")

In [3]:
df

,Unnamed: 0,network,image_idx,target_cls,delta,linna_time (seconds),linna_timeout,linna_is_real_cex,linna_result,linna_error,marabou_time (seconds),marabou_timeout,marabou_result,marabou_error
0,0,MNIST_3x100,0,5,0.02,601.630930,True,NaN,timeout,False,2.213925,False,unsat,False
1,1,MNIST_3x100,0,5,0.05,1.881908,False,True,sat,False,601.118845,True,timeout,False
2,2,MNIST_3x100,1,0,0.02,601.662556,True,NaN,timeout,False,2.100090,False,unsat,False
3,3,MNIST_3x100,1,0,0.05,601.618121,True,NaN,timeout,False,601.109685,True,timeout,False
4,4,MNIST_3x100,2,4,0.02,601.600302,True,NaN,timeout,False,601.071532,True,timeout,False
5,5,MNIST_3x100,2,4,0.05,1.934259,False,False,sat,False,601.123087,True,timeout,False
6,6,MNIST_3x100,3,1,0.02,601.652127,True,NaN,timeout,False,2464.306053,False,unsat,False
7,7,MNIST_3x100,3,1,0.05,1.056353,False,False,sat,False,601.098159,True,timeout,False
8,8,MNIST_3x100,4,9,0.02,601.661574,True,NaN,timeout,False,601.112192,True,timeout,False
9,9,MNIST_3x100,4,9,0.05,1.953323,False,True,sat,False,601.158500,True,timeout,False
10,10,MNIST_3x100,5,2,0.02,601.620212,True,NaN,timeout,False,9.298167,False,unsat,False
11,11,MNIST_3x100,5,2,0.05,1.135106,False,True,sat,False,601.244181,True,timeout,False
12,12,MNIST_3x100,6,1,0.02,601.605084,True,NaN,timeout,False,601.073099,True,timeout,False
13,13,MNIST_3x100,6,1,0.05,1.233305,False,True,sat,False,601.170408,True,timeout,False
14,14,MNIST_3x100,7,3,0.02,601.626197,True,NaN,timeout,False,2.117621,False,unsat,False
15,15,MNIST_3x100,7,3,0.05,601.673269,True,NaN,timeout,False,601.151110,True,timeout,False
16,16,MNIST_3x100,8,1,0.02,601.616067,True,NaN,timeout,False,601.099448,True,timeout,False
17,17,MNIST_3x100,8,1,0.05,1.040402,False,True,sat,False,601.116383,True,timeout,False
18,18,MNIST_3x100,9,4,0.02,601.621417,True,NaN,timeout,False,38.040918,False,unsat,False
19,19,MNIST_3x100,9,4,0.05,601.690439,True,NaN,timeout,False,601.105885,True,timeout,False

,Unnamed: 0,network,image_idx,target_cls,delta,linna_time (seconds),linna_timeout,linna_is_real_cex,linna_result,linna_error,marabou_time (seconds),marabou_timeout,marabou_result,marabou_error
1,1,MNIST_3x100,0,5,0.05,1.881908,False,True,sat,False,601.118845,True,timeout,False
9,9,MNIST_3x100,4,9,0.05,1.953323,False,True,sat,False,601.158500,True,timeout,False
11,11,MNIST_3x100,5,2,0.05,1.135106,False,True,sat,False,601.244181,True,timeout,False
13,13,MNIST_3x100,6,1,0.05,1.233305,False,True,sat,False,601.170408,True,timeout,False
17,17,MNIST_3x100,8,1,0.05,1.040402,False,True,sat,False,601.116383,True,timeout,False