In [1]:
import pandas as pd

## Marabou Data

In [41]:
df_marabou = pd.read_csv("marabou/20230131-095313.csv")

def process_marabou(df):
    df = df.set_index(["image_idx", "delta"])
    return df

df_marabou = process_marabou(df_marabou)

In [42]:
df_marabou

                 Unnamed: 0 dataset network_name  image_cls  timeout  \
image_idx delta
0         0.02            0   MNIST  MNIST_3x100          5      300
          0.05            1   MNIST  MNIST_3x100          5      300
1         0.02            2   MNIST  MNIST_3x100          0      300
          0.05            3   MNIST  MNIST_3x100          0      300
2         0.02            4   MNIST  MNIST_3x100          4      300
          0.05            5   MNIST  MNIST_3x100          4      300
3         0.02            6   MNIST  MNIST_3x100          1      300
          0.05            7   MNIST  MNIST_3x100          1      300
4         0.02            8   MNIST  MNIST_3x100          9      300
          0.05            9   MNIST  MNIST_3x100          9      300
5         0.02           10   MNIST  MNIST_3x100          2      300
          0.05           11   MNIST  MNIST_3x100          2      300
6         0.02           12   MNIST  MNIST_3x100          1      300
          0.05           13   MNIST  MNIST_3x100          1      300
7         0.02           14   MNIST  MNIST_3x100          3      300
          0.05           15   MNIST  MNIST_3x100          3      300
8         0.02           16   MNIST  MNIST_3x100          1      300
          0.05           17   MNIST  MNIST_3x100          1      300
9         0.02           18   MNIST  MNIST_3x100          4      300
          0.05           19   MNIST  MNIST_3x100          4      300
10        0.02           20   MNIST  MNIST_3x100          3      300
          0.05           21   MNIST  MNIST_3x100          3      300
11        0.02           22   MNIST  MNIST_3x100          5      300
          0.05           23   MNIST  MNIST_3x100          5      300
12        0.02           24   MNIST  MNIST_3x100          3      300
          0.05           25   MNIST  MNIST_3x100          3      300
13        0.02           26   MNIST  MNIST_3x100          6      300
          0.05           27   MNIST  MNIST_3x100          6      300
14        0.02           28   MNIST  MNIST_3x100          1      300
          0.05           29   MNIST  MNIST_3x100          1      300
15        0.02           30   MNIST  MNIST_3x100          7      300
          0.05           31   MNIST  MNIST_3x100          7      300
16        0.02           32   MNIST  MNIST_3x100          2      300
          0.05           33   MNIST  MNIST_3x100          2      300
17        0.02           34   MNIST  MNIST_3x100          8      300
          0.05           35   MNIST  MNIST_3x100          8      300
18        0.02           36   MNIST  MNIST_3x100          6      300
          0.05           37   MNIST  MNIST_3x100          6      300
19        0.02           38   MNIST  MNIST_3x100          9      300
          0.05           39   MNIST  MNIST_3x100          9      300
20        0.02           40   MNIST  MNIST_3x100          4      300
          0.05           41   MNIST  MNIST_3x100          4      300
21        0.02           42   MNIST  MNIST_3x100          0      300
          0.05           43   MNIST  MNIST_3x100          0      300
22        0.02           44   MNIST  MNIST_3x100          9      300
          0.05           45   MNIST  MNIST_3x100          9      300
23        0.02           46   MNIST  MNIST_3x100          1      300
          0.05           47   MNIST  MNIST_3x100          1      300
24        0.02           48   MNIST  MNIST_3x100          1      300
          0.05           49   MNIST  MNIST_3x100          1      300
25        0.02           50   MNIST  MNIST_3x100          2      300
          0.05           51   MNIST  MNIST_3x100          2      300
26        0.02           52   MNIST  MNIST_3x100          4      300
          0.05           53   MNIST  MNIST_3x100          4      300
27        0.02           54   MNIST  MNIST_3x100          3      300

                 marabou_time (seconds)  marabou_timeout  \
image_idx delta
0         0.02                 2.206431            False
          0.05               301.089843             True
1         0.02                 2.095545            False
          0.05               301.112031             True
2         0.02               301.085341             True
          0.05               301.097890             True
3         0.02               301.058009             True
          0.05               301.107866             True
4         0.02               301.063277             True
          0.05               301.136415             True
5         0.02                 9.127815            False
          0.05               301.099672             True
6         0.02               301.087630             True
          0.05               301.170004             True
7         0.02                 2.104749            False
          0.05               301.094485             True
8         0.02               301.097729             True
          0.05                 0.889166            False
9         0.02                33.576633            False
          0.05               301.117016             True
10        0.02                 2.249271            False
          0.05               301.087589             True
11        0.02               301.120871             True
          0.05                 0.610833            False
12        0.02                 2.126198            False
          0.05               301.084133             True
13        0.02                 2.334734            False
          0.05               301.137510             True
14        0.02               301.198812             True
          0.05                 0.525094            False
15        0.02               482.740536            False
          0.05                 0.404708            False
16        0.02               301.081807             True
          0.05               301.091334             True
17        0.02               301.139108             True
          0.05               301.148271             True
18        0.02               301.159041             True
          0.05                 0.398333            False
19        0.02               301.070850             True
          0.05                 0.715560            False
20        0.02                 2.350770            False
          0.05               301.103421             True
21        0.02                 2.118866            False
          0.05               301.088136             True
22        0.02               301.079540             True
          0.05                 0.874725            False
23        0.02               624.040833            False
          0.05               301.117319             True
24        0.02               301.097199             True
          0.05                 0.427552            False
25        0.02                 2.201437            False
          0.05               301.105045             True
26        0.02               301.158109             True
          0.05                 0.675611            False
27        0.02                 2.165143            False

                                                       marabou_cex  \
image_idx delta
0         0.02                                                 NaN
          0.05                                                 NaN
1         0.02                                                 NaN
          0.05                                                 NaN
2         0.02                                                 NaN
          0.05                                                 NaN
3         0.02                                                 NaN
          0.05                                                 NaN
4         0.02                                                 NaN
          0.05                                                 NaN
5         0.02                                                 NaN
          0.05                                                 NaN
6         0.02                                                 NaN
          0.05                                                 NaN
7         0.02                                                 NaN
          0.05                                                 NaN
8         0.02                                                 NaN
          0.05   [0.05, -0.05, -0.05, -0.05, -0.05, -0.05, -0.0...
9         0.02                                                 NaN
          0.05                                                 NaN
10        0.02                                                 NaN
          0.05                                                 NaN
11        0.02                                                 NaN
          0.05   [0.05, -0.05, 0.05, 0.05, -0.05, 0.05, -0.05, ...
12        0.02                                                 NaN
          0.05                                                 NaN
13        0.02                                                 NaN
          0.05                                                 NaN
14        0.02                                                 NaN
          0.05   [-0.05, -0.05, -0.05, -0.05, -0.05, 0.05, -0.0...
15        0.02                                                 NaN
          0.05   [-0.05, -0.05, -0.05, 0.05, -0.05, -0.05, 0.05...
16        0.02                                                 NaN
          0.05                                                 NaN
17        0.02                                                 NaN
          0.05                                                 NaN
18        0.02                                                 NaN
          0.05   [-0.05, -0.05, -0.05, 0.05, 0.05, 0.05, 0.05, ...
19        0.02                                                 NaN
          0.05   [0.05, 0.05, -0.05, 0.05, -0.05, -0.05, -0.05,...
20        0.02                                                 NaN
          0.05                                                 NaN
21        0.02                                                 NaN
          0.05                                                 NaN
22        0.02                                                 NaN
          0.05   [0.05, 0.05, -0.05, -0.05, -0.05, -0.014290894...
23        0.02                                                 NaN
          0.05                                                 NaN
24        0.02                                                 NaN
          0.05   [0.05, -0.05, 0.05, -0.05, 0.05, 0.05, -0.05, ...
25        0.02                                                 NaN
          0.05                                                 NaN
26        0.02                                                 NaN
          0.05   [-0.05, -0.05, -0.05, -0.05, 0.05, -0.05, -0.0...
27        0.02                                                 NaN

                marabou_result  marabou_error
image_idx delta
0         0.02           unsat          False
          0.05         timeout          False
1         0.02           unsat          False
          0.05         timeout          False
2         0.02         timeout          False
          0.05         timeout          False
3         0.02         timeout          False
          0.05         timeout          False
4         0.02         timeout          False
          0.05         timeout          False
5         0.02           unsat          False
          0.05         timeout          False
6         0.02         timeout          False
          0.05         timeout          False
7         0.02           unsat          False
          0.05         timeout          False
8         0.02         timeout          False
          0.05             sat          False
9         0.02           unsat          False
          0.05         timeout          False
10        0.02           unsat          False
          0.05         timeout          False
11        0.02         timeout          False
          0.05             sat          False
12        0.02           unsat          False
          0.05         timeout          False
13        0.02           unsat          False
          0.05         timeout          False
14        0.02         timeout          False
          0.05             sat          False
15        0.02           unsat          False
          0.05             sat          False
16        0.02         timeout          False
          0.05         timeout          False
17        0.02         timeout          False
          0.05         timeout          False
18        0.02         timeout          False
          0.05             sat          False
19        0.02         timeout          False
          0.05             sat          False
20        0.02           unsat          False
          0.05         timeout          False
21        0.02           unsat          False
          0.05         timeout          False
22        0.02         timeout          False
          0.05             sat          False
23        0.02           unsat          False
          0.05         timeout          False
24        0.02         timeout          False
          0.05             sat          False
25        0.02           unsat          False
          0.05         timeout          False
26        0.02         timeout          False
          0.05             sat          False
27        0.02           unsat          False

## LiNNA one linear combination

In [43]:
df_linna1 = pd.read_csv("linna_one_bound/20230131-110449.csv")

def process_linna1(df):
    return df

df_linna1 = process_linna1(df_linna1)
df_linna1

,Unnamed: 0,dataset,network_name,image_idx,image_cls,delta,timeout,reduction_rate,linna_time (seconds),linna_timeout,linna_is_real_cex,linna_cex,linna_result
0,0,MNIST,MNIST_3x100,0,5,0.02,300,0.05,7.465941,False,NaN,NaN,unsat
1,1,MNIST,MNIST_3x100,0,5,0.02,300,0.10,26.992524,False,NaN,NaN,unsat
2,2,MNIST,MNIST_3x100,0,5,0.02,300,0.25,334.037783,True,NaN,NaN,timeout
3,3,MNIST,MNIST_3x100,0,5,0.02,300,0.40,49.267662,False,False,"[-0.02, -0.02, 0.02, 0.02, 0.02, 0.02, -0.02, ...",sat
4,4,MNIST,MNIST_3x100,0,5,0.05,300,0.05,306.798039,True,NaN,NaN,timeout
...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,131,MNIST,MNIST_3x100,28,2,0.02,300,0.40,485.644078,True,NaN,NaN,timeout
132,132,MNIST,MNIST_3x100,29,7,0.05,300,0.05,6.006794,False,True,"[-0.05, -0.05, -0.05, -0.05, 0.05, -0.05, -0.0...",sat
133,133,MNIST,MNIST_3x100,29,7,0.05,300,0.10,13.427014,False,False,"[0.05, -0.05, 0.05, 0.05, 0.05, -0.05, -0.05, ...",sat
134,134,MNIST,MNIST_3x100,29,7,0.05,300,0.25,36.951520,False,False,"[0.05, -0.05, 0.05, 0.05, 0.05, -0.05, -0.05, ...",sat
135,135,MNIST,MNIST_3x100,29,7,0.05,300,0.40,50.622438,False,False,"[-0.05, -0.05, -0.05, -0.05, 0.05, 0.05, -0.05...",sat

In [44]:
df_joined = df_linna1.join(df_marabou, on=["image_idx", "delta"], rsuffix="_marabou")

In [61]:
df_joined[(df_joined.linna_result == 'unsat') & (df_joined.marabou_result == 'unsat')].reduction_rate.value_counts()

0.05    14
0.10    11
0.40     2
Name: reduction_rate, dtype: int64

## LiNNA two combinations

In [62]:
df_linna2 = pd.read_csv("linna_two_bounds/20230131-095833.csv")

In [63]:
df_linna2.linna_is_real_cex.value_counts()

False    176
True       9
Name: linna_is_real_cex, dtype: int64

In [64]:
df_linna2.linna_result.value_counts()

sat        185
timeout     35
Name: linna_result, dtype: int64

In [65]:
df_linna2

,Unnamed: 0,dataset,network_name,image_idx,image_cls,delta,timeout,reduction_rate,linna_time (seconds),linna_timeout,linna_is_real_cex,linna_cex,linna_result
0,0,MNIST,MNIST_3x100,0,5,0.02,300,0.05,303.012196,True,NaN,NaN,timeout
1,1,MNIST,MNIST_3x100,0,5,0.02,300,0.10,4.560551,False,False,"[-0.02, 0.02, 0.02, -0.02, 0.02, 0.02, 0.02, 0...",sat
2,2,MNIST,MNIST_3x100,0,5,0.02,300,0.25,6.343875,False,False,"[0.02, -0.02, 0.02, -0.02, 0.02, -0.02, 0.02, ...",sat
3,3,MNIST,MNIST_3x100,0,5,0.02,300,0.40,6.220339,False,False,"[-0.02, 0.02, -0.02, -0.02, -0.02, -0.02, 0.02...",sat
4,4,MNIST,MNIST_3x100,0,5,0.05,300,0.05,302.423151,True,NaN,NaN,timeout
...,...,...,...,...,...,...,...,...,...,...,...,...,...
215,215,MNIST,MNIST_3x100,26,4,0.05,300,0.40,6.914306,False,False,"[-0.05, 0.05, 0.05, 0.05, -0.05, 0.05, 0.05, -...",sat
216,216,MNIST,MNIST_3x100,27,3,0.02,300,0.05,302.419792,True,NaN,NaN,timeout
217,217,MNIST,MNIST_3x100,27,3,0.02,300,0.10,2.671209,False,False,"[-0.02, 0.02, -0.02, 0.02, -0.02, 0.02, -0.02,...",sat
218,218,MNIST,MNIST_3x100,27,3,0.02,300,0.25,6.344909,False,False,"[0.02, 0.02, -0.02, -0.02, 0.02, 0.02, -0.02, ...",sat
219,219,MNIST,MNIST_3x100,27,3,0.02,300,0.40,7.704165,False,False,"[-0.02, -0.02, 0.02, -0.02, -0.02, -0.02, 0.02...",sat